server:
  port: 8888
  servlet:
    contextPath: /api

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(R2nqa5S1PLorulyXew3kVAdCJZ0a34DRPj3tnFufgFJcIEls0ORTQZeAHNLikWVrh77/87krS/y/ozHaUcAiVw==)
    username: ENC(Z3DRbNy1esOpV8b69GI3+A==)
    password: ENC(Gan03/lHLMOXr7ICa7DUGFWM+QuQFbnu)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(Aw8ShjNwMn12bF4ld8d9w777CiYSpgUJ9XmLjJ/jyN+RXo7/eUwaLA==)
    password: ENC(0bPLCU4y/iWmn1HWlUjr5N5HZVOx5X38p0SpnPtDv/Y=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml


springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
  path: /swagger-ui.html
  disable-swagger-default-url: true
  display-query-params-without-oauth2: true
  paths-to-match:
    - /v1/**

logging:
  level:
    org.springframework.batch: info
    jdbc: debug
    jdbc.sqltiming: info
    jdbc.resultsettable: info
