server:
  port: 8888
  servlet:
    contextPath: /api

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(R2nqa5S1PLorulyXew3kVAdCJZ0a34DRPj3tnFufgFJcIEls0ORTQZeAHNLikWVrh77/87krS/y/ozHaUcAiVw==)
    username: ENC(Z3DRbNy1esOpV8b69GI3+A==)
    password: ENC(Gan03/lHLMOXr7ICa7DUGFWM+QuQFbnu)
mybatis:
  mapper-locations: classpath:mapper/**/*.xml