package com.tripmate.domain.common;

public interface ConstCode {
    String DUPLICATION_CHECK_CODE = "MB005";
    String DUPLICATION_CHECK_MEMBER_ID = "10";
    String DUPLICATION_CHECK_NICK_NAME = "20";
    String DUPLICATION_CHECK_EMAIL = "30";

    String EMAIL_TYPE_CODE = "MB004";
    String EMAIL_TYPE_CODE_JOIN = "10";
    String EMAIL_TYPE_CODE_EMAIL_CHANGE = "20";

    String MEMBER_STATUS_CODE = "MB002";
    String MEMBER_STATUS_CODE_COMPLETE = "10";
    String MEMBER_STATUS_CODE_TEMPORARY = "20";
    String MEMBER_STATUS_CODE_WITHDRAW = "30";
    String MEMBER_STATUS_CODE_ISSUE_TEMPORARY_PASSWORD = "40";

    String ATTRIBUTE_TYPE_CODE = "CT003";
    String ATTRIBUTE_TYPE_CODE_HASHTAG = "10";
    String ATTRIBUTE_TYPE_CODE_TRIP_THEME = "20";

    String NOTIFICATION_TYPE_CODE = "CT002";
    String NOTIFICATION_TYPE_CODE_TRIP_SCHEDULE = "10";
    String NOTIFICATION_TYPE_CODE_CHANGE_LEADER = "20";
    String NOTIFICATION_TYPE_CODE_INVITATION = "30";

    String CHECKLIST_TYPE_CODE = "CT004";
    String CHECKLIST_TYPE_CODE_MY = "10";
    String CHECKLIST_TYPE_CODE_TOGETHER = "20";

    String  STATISTICS_TERM_CODE = "CT005";
    String  STATISTICS_TERM_CODE_1_MONTH = "10";
    String  STATISTICS_TERM_CODE_3_MONTH = "20";
}
